quotidian-ennui/bitbucket-pr

- bb-pr
To be able to run `bb-pr squash-merge` without providing a PR number.
- Added `get_pr_number` function
- Added function call to actions
- Let IDE format shell
1. Checkout a branch with PR.
2. Run `bb-pr squash-msg`
3. Checkout a new branch
4. Run `bb-pr squash-msg` - No PR error expected
> feat: get pr number based on current branch

- README.md
- bb-pr
Docs were not updated from the changes from (#5)
- update help text
> fix(doc): update docs to include branch/pr derivation

- bb-pr
Keep spacing the space regardless of input.
- replace double \ to ensure its not included in message
- remove leading and trailing line breaks from details
- ensure approvers is spaced correctly even when no SQUASHMERGESTART and SQUASHMERGEEND
- remove leading and trailing lines breaks from final output
- Message with `_` should be displayed with just `_` and not `\_`
- Changes and Approved
- No Changes and Approved
- Changes not approved
- No change and not approved
> feat: consistent formatting of message

- .github/workflows/check-pr.yml
- README.md
- bb-pr
If you forget to tick the 'close_source_branch' checkbox (it appears you can't default it in repo settings); then we can squash-merge without deleting the source branch post-merge.
- add 'close-branch' command
- add -D flag to squash-merge to close the branch
- add pr-title check to ci pipeline
- `bb-pr close-branch -c true 3` and edit the PR in question.
- Need to find a suitable PR to test `squash-merge -D` on when close-branch as set it to be 'false'
Note entirely happy about the argument parsing, seems like a lot of duplication.
> feat: add close_source-branch capability

- README.md
- bb-pr
To be able to review PRs locally by being able to checkout by PR number and not needing to know branch.
Example workflow:
```shell
$ bb-pr list
ID  TITLE                                URL
11  ....
$ bb-pr checkout 11
branch 'feat/checkout' set up to track 'origin/feat/checkout.
Switched to a new branch 'feat/checkout'
```
- add checkout action to switch to a branch based on PR number
> feat: add checkout command to switch branches

- bb-pr
Remove the gone remotes during switch back to default after the merge.
- add remote prune before delete
- switch using switch over checkout
> feat: prune origin during switch

- bb-pr
Because this happens if you're not in a git repo.
```shell
Ubuntu-22.04 ~
bsh ❯ bb-pr
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Tool that helps management of bitbucket pull requests from the commandline
```
- pipe discovery logging from git exec to /dev/null
- If you're not in a git repo, then you shouldn't see the 'fatal' lines any longer
- should be no impact on other actions.
> feat: pipe discovery logging from git exec to /dev/null

- bb-pr
Resolves #23
- capture the http_code from curl
- do a different JQ if the code !=200
On an unsuccessful merge attempt it should show something like
```sh
bsh ❯ bb-pr squash-merge
ID                     STATE
2 failed merge checks  ["At least 1 approval","No in progress builds on last commit"]
Operation failed...
```
> feat: capture the error code from squash

- README.md
- bb-pr
- completion.sh
Mostly because i'm lazy and can't spell.
- add completion.sh 
- add new command to be used in bash_profile
```shell
eval "$(./bb-pr completion)"
bb-pr <TAB>
```
> feat: add command bash completion

- bb-pr
When using `bb-pr completion`
```shell
if [ -d "$HOME/.local/share/ubuntu-dpm/quotidian-ennui/bitbucket-pr" ]; then
eval "$(bb-pr completion)"
fi
```
- switch to using readlink to find checkout directory
> fix: script directory follows symlinks

- bb-pr
Resolves #36
- capture JQ output and if null emit the raw output
> fix: show raw error output if not parseable

- README.md
- bb-pr
- completion.sh
Laziness and muscle memory to gh alias `co: pr checkout`
- add co as an alias to checkout
> feat: add alias for checkout as co

- bb-pr
Bitbucket is really helpful in adding links automatically, especially to Jira.
We don't want these links in commit message as it makes it hard to read in console.
- add regex to remove markdown links from description
1. Add markdown link to `SQUASHMERGE` contents of existing PR
2. Run `..../bb-pr squash-msg <pr>`
> feat: remove markdown links from description

- README.md
- bb-pr
If you include conventional commit footers inside the SQUASHMERGE block, then they are separated by new lines so the squash merge msg comes out like this, which is a little lame. 
```
feat!: XXX
- a 
- b
BREAKING-CHANGE: Environment variable changes
Ref: BB-497
Ref: BB-77
Ref: BB-101
Approved-By: QE
```
That's just a consequence of "newlines being considered a paragraph break, which is really \n\n". We can't just squash 2+ newlines into a single one because then we don't get the required "new line between the body + footer..."
By introducing a SQUASHMERGEFOOTERSTART/END block we can use `tr -s` to squash multiple newlines into something meaningful...
- added optional SQUASHMERGEFOOTER tag support
- use `tr` to squash multiple newlines
The result should be (if you add in the correct …
> feat: add explicit conventional footer support

- README.md
- bb-pr
- completion.sh
Who wants to goto a webpage to get a status?
- add status action that uses pullrequests & pullrequests/status
- add status to completion script
- The nominal parameter is the PR number, but will happily discover the PR number from your branch.
```shell
bsh ❯ bb-pr status
STATUS  JOB               URL
✅      Pipeline #2145    https://bitbucket.org/...
✅      Pipeline #2146    https://bitbucket.org/...
⌚      Build #2          https://bitbucket.org/...
NAME            APPROVED
Pythagoras      👀
Maynard Keynes  👍
```
> feat: add status command to show PR status

- bb-pr
Add some more information to the status 
- add the squash msg to the status output
No changes to flags, but if you run `bb-pr status` then you should get more information including a link to the actual PR in bitbucket (will be clickable in windows terminal etc).
> refactor: add the squash-msg to status

- README.md
- bb-pr
Because sometimes people can't view emojis... 
- Cascadia Code shows emojis in the terminal but not all the starship git branch ones.
- nerd font will likely show emojis (I use firacode)
- IntelliJ's terminal doesn't by default (apparently)
- add "BB_PR_DISABLE_EMOJIS" env var
- Rather than "eyes" you'll see null on a fresh new PR because the status can be approved | changes_requested | null
```shell
export BB_PR_DISABLE_EMOJIS=true
bb-pr status
bsh ❯ bb-pr status
>>> PR#22: https://bitbucket.org/.../nnn
NAME            APPROVED
Pythagoras      null
Euler           null
Archimedes      null
```
> feat: add env-var to disable emojis

- README.md
- bb-pr
Supports #65 by letting you see your uuid.
- add whoami command
APP TOKEN is required to contain the read-account scope; so it's probably now just realistic to have a `all-read-pr-write` token...
> feat: add bb-pr whoami command

- bb-pr
#87 introduced a bug whereby if the origin/branch does not exist locally then git fails, which means you never see the status
You might not have the branch pulled because
- you're out of date (you want to see the status on something that you've never worked on)
- you're looking at the status of a historical PR that has already squash-merged and deleted the branch
- add || true when doing git rev-list
- Select a PR that's already been merged, and the corresponding branch has been deleted.
- `bb-pr status NNN` should still work, but not tell you about how many commits you are behind.
> fix: protect against missing branch

- bb-pr
- completion.sh
`squash-msg` kinda breaks completion (since you have to type so much), so rename squash-msg into something more autocomplete friendly
- switch squash-msg for message in completion script
- make squash-msg an alias for message (like co is).
- `bb-pr squash-msg 581` -> still works but emits an extra log message
- `bb-pr message 581` -> works as you'd expect
- `bb-pr m<tab>` -> auto-completes.
> refactor: deprecate squash-msg for message

- includes/bb_checkout
- includes/common
fzf is for life, not just for christmas?
Wherever we have an activity where we require a pr number to checkout, then we can delegate that to `fzf` if we cannot work out what it is that we want.
- refactor fzf use out of bb_checkout into common
- refactor get_pr_number to use fzf if autodetect fails
> Of course, it requires fzf to be on the path; if it is not on the path, then no fzf magic happens and behaviour should be as expected (i.e. `bb-pr status` will fail on the main branch)
- `bb-pr co` will bring up all the PRs
- `bb-pr status` will bring up all the PRs 
- ... and so on and so forth
- `bb-pr status` will just bring up the status
- `bb-pr draft` will make that PR draft
> feat: enable fzf wherever PR number is required

- includes/bb_status
- includes/common
Because I wanted to see the number of comments on a PR
- show comment count in extended status
- use __bb_rest_invoke method in bb_status
> Will just appear if you do `bb-pr status 748` or something
> feat: add comment_count to extended info

- includes/common
Finally hit a situation where we have > 1 page of PRs.
On main you get something like this, if you trigger a bb-list and you have a page2.
```
ID   TITLE                        URL
789  refactor: PR titlexyz        https://bitbucket.org/path.toPR
790  feat(scope): PR title        https://bitbucket.org/path.toPR
801  refactor(scope): PR titlexyz https://bitbucket.org/path.toPR
803  refactor(scope): PR titlexyz https://bitbucket.org/path.toPR
804  feat(scope): PR titlexyz     https://bitbucket.org/path.toPR
805  refactor(scope): PR titlexyz https://bitbucket.org/path.toPR
806  refactor(scope): PR titlexyz https://bitbucket.org/path.toPR
807  refactor(scope): PR title    https://bitbucket.org/path.toPR740 feat(scope): blah https
808  refactor(scope): PR titlexyz …
```
> fix: extra pages causes poor table layout for list operation
